# Setup
title:               Andre Ye
tagline:             'Writing and Ideas'
description:         'Writing and Ideas.'
url:                 https://andre-ye.github.io
baseurl:             /pub
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andre Ye
  url:               https://andre-ye.github.io
  email:             andre-ye@uw.edu

# Gems
plugins:
  - jekyll-paginate
