# Setup
title:               I2 Pub
tagline:             'Interactive Intelligence'
description:         'Articles on AI, neuroscience, philosophy.'
url:                 https://interactive-intelligence.github.io
baseurl:             /pub
paginate:            5
permalink:           pretty

# # About/contact
# author:
#   name:              Mark Otto
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
