# Setup
title:               I2 Pub
tagline:             'Pub - Interactive Intelligence'
description:         'Articles on .'
url:                 https://interactive-intelligence.github.io/pub
baseurl:             ''
paginate:            5
permalink:           pretty

# # About/contact
# author:
#   name:              Mark Otto
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
